version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:
          name: Build, test and verify
          command: mvn clean verify

      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run:
          name: Upload coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) \
              -f target/site/jacoco/jacoco.xml

workflows:
  build:
    jobs:
      - build